### ISSUE TITLE
Android app stuck in `Loading...`

### ISSUE THREAD

**Issue by chrishobcroft** [OrchidTechnologies/orchid#102]
# Summary

When using the Orchid app for Android, a "Loading..." message appears while attempting to "+ Add Credit", and doesn't ever "Load".

# Steps To Reproduce

0. Download [Orchid apk from github](https://github.com/OrchidTechnologies/orchid/releases)
1. Install on Android device (LineageOS 18.1)
2. Open app and tap on "Manage Accounts"
3. Tap on "+ Add Credit"
4. Observe the "Current avg. VPN price is" message update to $0.06 per GB

# Expected Behaviour 

I expect something to load. I'm not sure what though. Perhaps a credit balance.

# Screen Capture

https://user-images.githubusercontent.com/2212651/126684758-2b970bc7-37b9-444d-8ead-3993e844dc0e.mp4

# Environment

 - Device: Google Pixel 3
 - OS: `LineageOS 18.1`
 - Build Number: `lineage_blueline-userdebug 11 RQ3A.210705.001 fb4354a092`
 - Application Version: `0.9.29 (678920814)`

**Comment by chrishobcroft** [comment]
Verified as still not working on Build Number: `lineage_blueline-userdebug 11 RQ3A.210705.001 ad42774a96`

**Comment by saurik** [comment]
This issue has been fixed in commit 47694828a333aa2b6f897e20d77fac70d2698001, which will be part of our next release (and which we expect to happen soon: I think we are still just sorting out our translations).

**Comment by chrishobcroft** [comment]
Thank you.
