### ISSUE TITLE
Support other protocols ? Like, geph and shadowsocks

### ISSUE THREAD

**Issue by planetoryd** [OrchidTechnologies/orchid#137]
**Is your feature request related to a problem? Please describe.**

I haven't tried it yet, but based on my experience many protocols are easily detected and blocked by GFW. I have no expertise on this topic though. China has a large market for VPN because of the GFW (millions of users). Chinese people have developed specialized protocols like shadowsocks, v2ray and now [geph](https://github.com/geph-official/geph4). Apparently the reason is that usual protocols fail.

Also, Chinese need anonymous crypto payments or Alipay.

**Describe the solution you'd like**

I wonder if your currently supported protocols are resistant to GFW, which should be the most sophisticated firewall, and if your products penetrates GFW, it would be unstoppable. 

**Describe alternatives you've considered**

or your protocol is censorship-resistant enough.

**Comment by saurik** [comment]
We have a team of users who had recently tested our product in China and AFAIK it is currently functional. It could be that I missed the current status, however. It also--of course--already uses our probablistic nanopayments cryptocurrency payment model (though some of our pricing model code doesn't work if you are in China; I believe most currencies we support should work, though). If you have a concrete issue with the mechanism not functioning for you, please either re-open this ticket or contact us directly.

**Comment by planetoryd** [comment]
The government upgrades their firewall frequently. In any case, you need to be prepared.
