### ISSUE TITLE
I'd like to join, but this is just a smartphone app

### ISSUE THREAD

**Issue by mirimir** [OrchidTechnologies/orchid#16]
And OK, that's not exactly what I want to say, but I'm stuck with it.

The issue is that the instructions in the "Orchid is live + OXT available on Coinbase!" email involve the Android Orchid app. And I don't use smartphones. 

But then there's this repository. Which obviously includes some Linux stuff. But I can't tell from casual inspection just what it is. However, I'll install it in a Ubuntu VM, and see.

Still, even if there is a Linux client, there's this: `The Orchid app is where you manage your private path to the Internet by constructing custom “hops” on our new VPN platform. To fund your hops, you will need to connect them to your funding source via your Orchid account.`

I never imagined that requirement. And in my defense, I just reread the README.md, and "phone" doesn't appear there. So maybe it'd be helpful to say that up front.

Anyway, given that I own some OXT already, I'll try installing the Orchid app in an Android-x86 VM in VirtualBox. If that doesn't work, I guess that this isn't for me.

Unless there's some other workaround to use Orchid in Linux. That would be cool.

**Comment by mirimir** [comment]
OK, I installed the Orchid app in an Android-x86 9.0-rc1 VM. It has a virtual WiFi adapter that seems to work. Well enough for Google, anyway.

However, the Orchid app won't run. But other apps seem fine.

So it goes.

**Comment by nhandler** [comment]
At the moment, Orchid does not support the Android x86 or x86_64 emulators. It should still be possible to use the Android app from within an emulator, but you will need to emulate an ARM device. We will be sure to post updates once we are ready to support clients for other platofrms.
