### ISSUE TITLE
Cairo and other freedesktop submodules fail to clone

### ISSUE THREAD

**Issue by rarigita** [OrchidTechnologies/orchid#164]
**Describe the bug**
While following instructions to compile the source from github into a linux box, cairo submodules and other freedesktop repos fails to clone.

**To Reproduce**
$ git clone https://github.com/OrchidTechnologies/orchid.git
$ cd orchid
$ git submodule update --init --recursive
Clonando en '/orchid/min-cairo/cairo'...
Username for 'https://github.com': **
Password for 'https://**@github.com': 
remote: Repository not found.
fatal: repositorio 'https://github.com/freedesktop/cairo.git/' no encontrado

**Expected behavior**
Repository cloned like the other submodules

**Screenshots**

**Device information:**
Kali Linux latest

**Additional context**
Not sure if freedesktop repos are publicly accesible (or with github account) or they have been moved.

**Comment by saurik** [comment]
Sorry: Freedesktop seems to have moved off of GitHub and has switched to a self-hosted GitLab instance (which, FWIW, is a decision I applaud). I've updated the .gitmodule URLs.
