### ISSUE TITLE
Clarify supported platforms and provide clear usage/install instructions

### ISSUE THREAD

**Issue by elsesiy** [OrchidTechnologies/orchid#17]
**Describe the bug**
The website currently only lists `iOS` (via Testflight) and the `apk` download for Android. However the releases section on GH shows bundles for `mac` and `lnx` which raises the question as to whether there's a Desktop client and how to install/use it.

**To Reproduce**
n/a

**Expected behavior**
Clear instructions for all supported platforms incl. installation instructions e.g. homebrew, apt, etc.

**Screenshots**
n/a

**Device information:**
n/a

**Additional context**
n/a

**Comment by saurik** [comment]
As this is a code repository, you are going to see a lot of releases and bundles and code for things that are in progress or only half-supported. As a great example: we technically have a command-line client for macOS and Linux that we use for debugging, but it is nowhere near ready for being distributed via something like homebrew, nor is it clear that is even the correct direction to go in (as the command line client has issues with how it interfaces with macOS's networking, and so should really be redone as a network extension).

So, for information on what is "supported" (which implies something much deeper than "technically exists" or "is being developed"), you definitely should be looking at the project's official website, which is as far as I know providing the most up-to-date and correct information (i.e. that there is an application available for Android in the Play Store, and we are currently in TestFlight on iOS). If and when we are prepared to support users on other platforms, the website will be updated at that time with "clear instructions" for installation.
