### ISSUE TITLE
Windows Beta is not working

### ISSUE THREAD

**Issue by MaHi177** [OrchidTechnologies/orchid#174]
There is no clear documentation. Is it hard to make a youtube video for the dev team? 

**I am encountering this error. If anyone is using Windows Beta, please help me. I believe the dev team is not alive.**

orchidcd-win.exe --config orchid.cfg

Ok.

Ok.

Ok.

Ok.

Ok.

[@:1712768837024326] [T:4] [vpn/p2p/source/chainlink.cpp:42] handled error: [vpn/p2p/source/endpoint.cpp:52] {"code":-32000,"message":"execution reverted"} [vpn/p2p/source/endpoint.cpp:58] calling eth_call on https://ethereum-rpc.publicnode.com:443/ [./vpn/p2p/source/chain.hpp:386] calling latestAnswer() with ()
[@:1712768838650239] [T:4] [./vpn/p2p/source/retry.hpp:71] handled error: [./vpn/source/heap.hpp:103] undefined hops[0].rpc [vpn/source/capture.cpp:732] building hop #0
[@:1712768838927248] [T:4] [vpn/p2p/source/chainlink.cpp:42] handled error: [vpn/p2p/source/endpoint.cpp:52] {"code":-32000,"message":"execution reverted"} [vpn/p2p/source/endpoint.cpp:58] calling eth_call on https://ethereum-rpc.publicnode.com:443/ [./vpn/p2p/source/chain.hpp:386] calling latestAnswer() with ()
[@:1712768839984880] [T:4] [./vpn/p2p/source/retry.hpp:71] handled error: [./vpn/source/heap.hpp:103] undefined hops[0].rpc [vpn/source/capture.cpp:732] building hop #0

1. I have export the configurations and put in the "**orchid.cfg**" file like this

`hops = [
  {
    protocol: "orch1d",
    curator: "partners.orch1d.eth",
    funder: "my funding acc",
    secret: "my secret",
    chainid: 100,
    currency: "DAI"
  }
];

rpc = "https://ethereum-rpc.publicnode.com";
`

2. I tried with admin cmd like this "**orchidcd-win.exe --config orchid.cfg**". I am getting above error. 

if anyone using orchild in windows. please help me. I really like this VPN. but dev team is dead or they run away with collected funds  we don't have choice.

**Comment by MaHi177** [comment]
hops = [
  {
    protocol: "orch1d",
    curator: "partners.orch1d.eth",
    funder: "0xAC--this is my funder ID I took it from mobile app",
    secret: "0x7d--this is my secret ID I took it from mobile app",
    chainid: 100,
    currency: "DAI", //in my android app it's showing balance in DAI
    rpc: "https://rpc.xdaichain.com/"
  }
];
rpc = "https://ethereum.publicnode.com";



I save it as "**orchid.cfg**"

then, with admin cmd I tired 
**orchidcd-win.exe --config orchid.cfg**


This is the log

> orchidcd-win.exe --config orchid.cfg

Ok.

Ok.

Ok.

Ok.

Ok.

[@:1712766440580672] [T:4] [vpn/p2p/source/chainlink.cpp:42] handled error: [vpn/p2p/source/endpoint.cpp:52] {"code":-32000,"message":"execution reverted"} [vpn/p2p/source/endpoint.cpp:58] calling eth_call on https://ethereum.publicnode.com:443/ [./vpn/p2p/source/chain.hpp:386] calling latestAnswer() with ()
[@:1712766440812063] [T:4] [./vpn/p2p/source/retry.hpp:71] handled error: [./vpn/p2p/source/buffer.hpp:377] orc_assert(value == size()) [vpn/source/capture.cpp:713] parsing .secret [vpn/source/capture.cpp:732] building hop #0
[@:1712766441093868] [T:4] [vpn/p2p/source/chainlink.cpp:42] handled error: [vpn/p2p/source/endpoint.cpp:52] {"code":-32000,"message":"execution reverted"} [vpn/p2p/source/endpoint.cpp:58] calling eth_call on https://ethereum.publicnode.com:443/ [./vpn/p2p/source/chain.hpp:386] calling latestAnswer() with ()
[@:1712766441108380] [T:4] [./vpn/p2p/source/retry.hpp:71] handled error: [./vpn/p2p/source/buffer.hpp:377] orc_assert(value == size()) [vpn/source/capture.cpp:713] parsing .secret [vpn/source/capture.cpp:732] building hop #0

**Comment by saurik** [comment]
Trying hard to ignore your clearly-incorrect and uncalled-for mean comment at the end :/...

If you are going to use an account with DAI you have to provide the RPC node for Gnosis Chain as part of your hop. Try adding `rpc: "https://rpc.gnosischain.com/"`?

```
hops = [
{
protocol: "orch1d",
curator: "partners.orch1d.eth",
funder: "my funding acc",
secret: "my secret",
chainid: 100,
rpc: "https://rpc.gnosischain.com/",
currency: "DAI"
}
];

rpc = "https://ethereum-rpc.publicnode.com/";
```
