### ISSUE TITLE
Bugs with duplicate dz-preview (field Orchid\Screen\Fields\Upload) and pictures in media 

### ISSUE THREAD

**Issue by GDogyGy** [OrchidTechnologies/orchid#175]
**Describe the bug**
When add field Upload to some element with {field: upload}->media() and turbo.cache = true this field duplicate dz-preview  when back to page. And when i click to media picture duplicate with same hash file.

**To Reproduce**
1. Go to list element and add element with 
`Upload::make('seoField.image_id')
                ->title(__('seo_field.admin.column.image'))->media()
                ->acceptedFiles('.jpg,.png,.jpeg')->maxFiles(1)`
3. Click on save and save another element with same picture
4. Reload page and use turbo cache return to list page and again return to element. You see duplicate
5. And other bug. Click to media in element page with field. Now file with same hash sum are duplicate.

**Expected behavior**
In media does not have duplicate with one sum hash
When i back in page with turbo cache i had to see one block preview dz-preview 

**Screenshots**
<img width="727" alt="Monosnap Обновить SEO-поле - Laravel 2024-05-03 18-44-17" src="https://github.com/OrchidTechnologies/orchid/assets/60182892/017f6f43-0fe4-4e28-b7c1-60d996ae2211">
![image](https://github.com/OrchidTechnologies/orchid/assets/60182892/38fb41db-7894-4ccb-b00e-4f4b9e5fb983)

**Device information:**
 - Device: [e.g. mackbook]
 - OS: [e.g. last]
 - Application Version [e.g. last]
 - Chrome

**Additional context**

**Comment by saurik** [comment]
It seems like you have us confused with a different product: I have no clue what any of this means.

**Comment by saurik** [comment]
@GDogyGy FTR, I think you wanted this repository: https://github.com/orchidsoftware/platform
