### ISSUE TITLE
Orchid not available on Google Play store? Links are dead

### ISSUE THREAD

**Issue by joebagadonuts0909** [OrchidTechnologies/orchid#177]
it appears Orchid is no where to be found on the google play store, was this taken down? Also the orchid Reddit thread appears to be dead, as well as the discord is broken or not accessible. Leaving a comment here as it appears to be the only place to get in contact with the team.

 Based on the people involved in this project and old videos of the VPN, this would appear to be a hugely popular project and im exited to try it out

- Any updates on the current status of the project? 
- Is the original team still working on this?
-  will orchid be available in the google play store anytime soon?
- will discord and/or reddit threads be brought back to life?

Thanks!
Joebagadonuts

**Comment by saurik** [comment]
The Orchid app was, in fact, removed by Google. This is something I am aware of and we are both working on submitting the various declarations as well as working on pushing an updated build (something broke in a UI dependency). I expect this to be rectified very soon.

In the mean time, you should be able to download an APK from the releases here and sideload it: it is signed with the same key. I will note that, while we do continue to support Google Play, the centralized stores are only somewhat helpful with respect to VPN technology :(.

FWIW, the original team certainly are still the people who are working on this: you can see that from the commits on this codebase (though I guess those could have been forged by someone and my GitHub account compromised? I am considering a move off GitHub...).

As for the reddit or Discord, I have never participated in either, and so do not know if they are functional. I am, in fact, quite opposed to the use of Discord on numerous fronts :/. That said, I have no reason to believe there is an issue, but also don't consider that a codebase issue.

I will leave this issue open until the app is once again available on Google Play. If you have further questions on the other topics, I encourage you to reach out to the Orchid support line (which might or hopefully might not involve talking to me again, wearing an uglier hat ;P).

**Comment by Bobesmj** [comment]
How i can add funds to orchid now? while i click "buy" button google play says "The item that you were attempting to purchase could not be found."

**Comment by saurik** [comment]
This was apparently fixed at some point (but no one told me until a few days ago ;P), so I am (finally) closing this issue.
