### ISSUE TITLE
Google Play Store "This app isn't available for your device because it was made for an older version of Android"

### ISSUE THREAD

**Issue by ew0k** [OrchidTechnologies/orchid#178]
**Describe the bug**
Go to download Orchid VPN app on Google Play Store. 
It says on the app page "This app isn't available for your device because it was for an older version of Android"

**To Reproduce**

On latest Google Pixel 9 running latest update Android 15. 

1. Go to orchid.com
2. Click on the google play store link to download app
3. Get redirected to Google PLay Store app page for Orchid VPN
4. No option to install or download because it says  "This app isn't available for your device because it was made for an older version of Android" 

It is also worth noting unless you click through the webpage the play store will not even show you the app. It is as if does not exist. 

**Expected behavior**
I expect to be able to install the app. 

**Device information:**
 - Device: Google Pixel 9
 - OS: Android 15

**Comment by saurik** [comment]
Sorry :(. FWIW, we believe this was fixed last week (but, as usual, I misread the internal message saying such). If you still experience this on your device/account, please reopen this issue.
