### ISSUE TITLE
App and website set-up guides differ materially

### ISSUE THREAD

**Issue by oideae** [OrchidTechnologies/orchid#21]
**Describe the bug**

The set-up guide within the app and the set-up guide on the website have _numerous_ substantive differences. These differences may cause confusion and/or frustration for new users—potentially having a negative affect on adoption.

**To Reproduce**

1. Note the prose on: `Menu` > `Help`
2. Note the prose on: `Hops` > `New Hop` > `I have a QR code` > [`Read the guide.`](https://www.orchid.com/join/)
3. Note the prose on: `Hops` > `New Hop` > `I want to try Orchid` > [`LEARN MORE`](https://www.orchid.com/join/)

**Expected behavior**

I would expect the app and website set-up guides not to differ materially.

**Screenshots**

Not applicable.

**Device information:**

Not applicable.

**Additional context**

This issue references the `iOS` application, via TestFlight, at version `0.9.5`, build `47.160426.1821548`.

**Comment by nhandler** [comment]
An update (https://github.com/OrchidTechnologies/orchid/commit/7d477e09efd089f6aeb6590f232c7b58edc88263) was pushed to bring the in-app help more in line with the docs on the website. For iOS TestFlight users, this should be available as of version 0.9.5 (47.247861.457358).
