### ISSUE TITLE
Build srv_shared on CentOS results in "Error in 'make':"

### ISSUE THREAD

**Issue by davenport651** [OrchidTechnologies/orchid#25]
**Describe the bug**
I attempted to build the srv_shared software on CentOS 7.  I followed the Ubuntu steps, substituting yum for apt-get.  There were no errors until I executed make -C srv-shared.  Instead of completing successfully, I received the following message:

 [root@host orchid]# make -C srv-shared
*** Error in `make': realloc(): invalid next size: 0x00000000016694c0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7f7c4)[0x7f3206f747c4]
/lib64/libc.so.6(+0x84bb1)[0x7f3206f79bb1]
/lib64/libc.so.6(realloc+0x1d2)[0x7f3206f7b162]
make[0x4135de]
make[0x40dea9]
make[0x40eac0]
make[0x419819]
make[0x419d87]
make[0x41ae10]
make[0x403c9f]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f3206f17505]
make[0x404346]
======= Memory map: ========
00400000-0042a000 r-xp 00000000 fd:03 399788                             /usr/bin/make
00629000-0062a000 r--p 00029000 fd:03 399788                             /usr/bin/make
0062a000-0062c000 rw-p 0002a000 fd:03 399788                             /usr/bin/make
0062c000-0062d000 rw-p 00000000 00:00 0 
01570000-01687000 rw-p 00000000 00:00 0                                  [heap]
7f31fc000000-7f31fc021000 rw-p 00000000 00:00 0 
7f31fc021000-7f3200000000 ---p 00000000 00:00 0 
7f32007b5000-7f32007ca000 r-xp 00000000 fd:03 418330                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f32007ca000-7f32009c9000 ---p 00015000 fd:03 418330                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f32009c9000-7f32009ca000 r--p 00014000 fd:03 418330                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f32009ca000-7f32009cb000 rw-p 00015000 fd:03 418330                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f32009cb000-7f3206ef5000 r--p 00000000 fd:03 418340                     /usr/lib/locale/locale-archive
7f3206ef5000-7f32070b8000 r-xp 00000000 fd:03 394687                     /usr/lib64/libc-2.17.so
7f32070b8000-7f32072b8000 ---p 001c3000 fd:03 394687                     /usr/lib64/libc-2.17.so
7f32072b8000-7f32072bc000 r--p 001c3000 fd:03 394687                     /usr/lib64/libc-2.17.so
7f32072bc000-7f32072be000 rw-p 001c7000 fd:03 394687                     /usr/lib64/libc-2.17.so
7f32072be000-7f32072c3000 rw-p 00000000 00:00 0 
7f32072c3000-7f32072e5000 r-xp 00000000 fd:03 424673                     /usr/lib64/ld-2.17.so
7f32074d4000-7f32074d7000 rw-p 00000000 00:00 0 
7f32074db000-7f32074e2000 r--s 00000000 fd:03 395003                     /usr/lib64/gconv/gconv-modules.cache
7f32074e2000-7f32074e4000 rw-p 00000000 00:00 0 
7f32074e4000-7f32074e5000 r--p 00021000 fd:03 424673                     /usr/lib64/ld-2.17.so
7f32074e5000-7f32074e6000 rw-p 00022000 fd:03 424673                     /usr/lib64/ld-2.17.so
7f32074e6000-7f32074e7000 rw-p 00000000 00:00 0 
7ffd8ada5000-7ffd8adc6000 rw-p 00000000 00:00 0                          [stack]
7ffd8adc6000-7ffd8adc8000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted
[root@host orchid]# 

**Device information:**
 - Device: VM web server
 - OS: CentOS 7 server (no window system)

[root@host orchid]# hostnamectl
   Static hostname: host..com
         Icon name: computer-vm
           Chassis: vm
    Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-957.27.2.el7.x86_64
      Architecture: x86-64
[root@host orchid]# rpm -qa centos-release
centos-release-7-7.1908.0.el7.centos.x86_64

**Additional context**
I'm not looking for support or a resolution.  I just wanted to leave this information in case it's useful to the developers as the software matures.

**Comment by saurik** [comment]
This is a bug in the version of GNU Make you are using. You might file this with Make, but I am also pretty sure this was fixed a long time ago, as I have some reason to believe I have only ever seen these crashes with old versions of Make 3.x. I think CentOS 7 is shipping Make 3.82? That release is almost a decade old at this point. Make 4.0 was released almost seven years ago, and they are currently on 4.3. Either upgrade Make or use a distribution with a useful version of Make.
