### ISSUE TITLE
Segfault with single OpenVPN hop

### ISSUE THREAD

**Issue by brandoncurtis** [OrchidTechnologies/orchid#30]
**Describe the bug**
Orchid VPN crashes silently when using a single OpenVPN hop.
The app says that the VPN is active, but the key icon disappears from the system bar and no traffic shows up in the traffic tab.

**To Reproduce**
1. Remove all existing hops
2. Configure a known-good OpenVPN hop
3. Activate the VPN
4. The key icon will appear in the system bar, and after a few seconds it will disappear
5. Do this repeatedly to receive an Android system message that "Orchid keeps stopping" and an invitation to submit a bug report

**Expected behavior**
A single hop with a known-good OpenVPN connection should work fine.
(connections work fine in the Android OpenVPN Connect app)

**Screenshots**
N/A

**Device information:**
 - Motorola Moto x4
 - Android Version 9 (Kernel 4.4.153)
 - Orchid v0.9.5.p169.g7d477e0 (634339283)

**Additional context**
N/A

**Comment by saurik** [comment]
Did you happen to submit that bug report? Maybe can you provide the crashlog? I'm just fascinated by this being a segfault... like if this were an assertion/exception I'd just say "oh, there's probably some awkward thing where OpenVPN3 requires a subtle tweak to your OVPN file vs. the OpenVPN2 which that Connect app is likely using", but an honest-to-goodness segmentation fault indicates something much more sinister that I'll need more context to debug. Maybe you can at least tell me what OpenVPN service provider you are using?

**Comment by saurik** [comment]
This seems to be an app front-end configuration file sterilization bug; if you replace all the beeline shows in your OpenVPN configuration file with "\n" and enter it as a single line it works ;P. This will be fixed soon, at which point I will close this issue.

**Comment by saurik** [comment]
This issue was fixed at some point and at some point sufficiently later than that to be surprising--but not so long for it to be ludicrous--this fix was shipped. If this is still not working for you, please re-open this issue ;P.
