### ISSUE TITLE
Trying to build, 'iostream' not found.

### ISSUE THREAD

**Issue by epr7142** [OrchidTechnologies/orchid#31]
**Description**
Cloned Repo and Tried to build according to readme in srv-shared.

During make, exits with following error:
-------------------------------------------
make[2]: Leaving directory '/orchid/srv-shared/out-lnx/x86_64/openssl'
make[1]: Leaving directory '/orchid/srv-shared/out-lnx/x86_64/openssl'
[CC] lnx/x86_64 p2p/./lz4/lib/lz4.c
[CC] lnx/x86_64 p2p/./lz4/lib/lz4frame.c
[CC] lnx/x86_64 p2p/./lz4/lib/lz4hc.c
[CC] lnx/x86_64 p2p/./lz4/lib/xxhash.c
[CC] lnx/x86_64 p2p/./openvpn3/client/ovpncli.cpp
p2p/./openvpn3/client/ovpncli.cpp:24:10: fatal error: 'iostream' file not found
#include <iostream>
         ^~~~~~~~~~
1 error generated.
make: *** [env/output.mk:163: out-lnx/x86_64/./p2p/./openvpn3/client/ovpncli.cpp.o] Error 1
---------------------------------------------------

But I can see iostream at /orchid/srv-shared/env/libcxx/include.
Is there some adjustment I need to make so it sees the include folder?

**Comment by epr7142** [comment]
Not closing issue, but updating. 

Was trying to build this form source on manjaro (Juhrya installer).
Was able to progress further by installing packages matching libc++* pattern. 

I will probably try running a node in a VM in the meantime, but this might prove useful for others trying to adventurously build on other platforms.

**Comment by chrishobcroft** [comment]
@epr7142 are you able to be any more specific about which packages need to be `sudo apt install`ed?

**Comment by saurik** [comment]
You need a working copy of a recent copy of clang on your system. While there were some legitimate issues with compiling on Linux without debug=crossndk (which is the configuration we always use) I have fixed these and added a regression build to the GitHub workflow CI, per #14, and am thereby closing this issue.
