### ISSUE TITLE
Impossible to build for android app

### ISSUE THREAD

**Issue by tatacharles** [OrchidTechnologies/orchid#36]
Hello,

I have an issue with android studio.

**Describe the bug**
Impossible to build the android source files. 
Android studio shows 2 errors :
1 -  Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'flutterJar' for root project 'app-android' of type org.gradle.api.Project.
2 - Caused by: java.lang.IllegalStateException: compileSdkVersion is not specified.

Do you think, there is a problem with my android studio version ? Or android SDK ?

Thank you,
Charles

**Comment by saurik** [comment]
We fundamentally do not support the usage of Android Studio to compile this project (and never will); drop to a command line in the app-android folder and type "make".
