### ISSUE TITLE
Anycast failed conversion using boost

### ISSUE THREAD

**Issue by nseidm1** [OrchidTechnologies/orchid#40]
Compilation on OSX successful. More documentation will help helpful in the future, a variety of additional dependencies are needed as compared to the limited information I was able to track down.

**To Reproduce**
Execute compiled orchidd: ./orchidd

**Expected behavior**
Running service.

**Screenshots**
Pastebin of run log: https://pastebin.com/xcLegyGb

**Device information:**
OSX Catalina. Compilation successful

**Additional context**
Terminating fault:
boost::bad_any_cast: failed conversion using boost::any_cast
libc++abi.dylib: terminating
Abort trap: 6

**Comment by saurik** [comment]
You have to pass command line arguments to configure the service: you can't just run the binary and have it work, as it needs access to ethereum accounts and the such. That error (which I admit is a really lame error to print) is it trying and failing to pull one of the missing command line arguments. I thereby like, appreciate the sentiment; but, given the reproduction steps of "run the binary without providing any configuration", this behavior is "expected".
