### ISSUE TITLE
Rounding Error causes Insufficient Fund Glitch

### ISSUE THREAD

**Issue by David-Berlin** [OrchidTechnologies/orchid#48]
When loading the DApp at account.orchid.com and prompted to fund your account, the DApp rounds the funding amount to two decimal places. If this causes the amount to be rounded up, the user receives an insufficient funds error. Either do not round the value (best option, in my opinion) or, instead of rounding, use a floor function.

**Comment by saurik** [comment]
I have been told that this was fixed: "I implemented a fix / guard to prevent it from every trying to spend more than the available wallet"; if this is still an issue, please re-open this issue (or potentially file a new one if it feels different).
