### ISSUE TITLE
Sign up process never completes

### ISSUE THREAD

**Issue by scarolan** [OrchidTechnologies/orchid#58]
**Describe the bug**
I attempted to follow the documentation to install and use the Orchid Android app. I got as far as transferring OXT and ETH into a supported smartphone wallet, then visiting account.orchid.com in the Web3 browser in the wallet.

**To Reproduce**
Follow the docs up to the initial account deposit of OXT and ETH.  Wait 12+ hours with no confirmation or progress.

**Expected behavior**
App sets up in <10 minutes and I am able to browse the web using Orchid VPN.

**Device information:**
 - Device: pixel xl
 - OS: latest android

**Comment by scarolan** [comment]
Some more troubleshooting reveals several failed transactions in the wallet.  Attempted to cancel and create an account again.  This time it says "transaction underpriced" yet there is no way to change the miner fee in Coinbase Wallet.

The documentation says:
**Note: we recommend editing the transaction fee and paying extra ETH for "fast" so that the Orchid account is created within 30-60 seconds. Paying for slow may cause the transactions to hang.**

There doesn't appear to be any way to pay extra ETH using your setup process in Coinbase Wallet.

**Comment by scarolan** [comment]
Screenshots showing a completely different error...

![Screenshot 2019-10-28 at 3 15 59 PM](https://user-images.githubusercontent.com/403332/90342930-bcfbd100-dfd1-11ea-9233-59abacdf1c2b.png)

![Screenshot 2019-10-26 at 3 04 15 PM](https://user-images.githubusercontent.com/403332/90342933-c1c08500-dfd1-11ea-8142-cbfd70b41405.png)

**Comment by dereksilva** [comment]
Hey there, sorry no one got back to you on this.

My recollection is that this was near the peak of the DeFi craze, and Coinbase Wallet wasn't able to keep up with Gas price fluctations. It should work perfectly now that Gas is relatively stable comparatively speaking.

**Comment by saurik** [comment]
I am closing this as likely a limitation at best and a bug at worst with Coinbase Wallet, particularly given the weird SQLite errors that resulted (and that I haven't heard of a similar issue since and it has been a long time).
