### ISSUE TITLE
cleanup github repo

### ISSUE THREAD

**Issue by Xyz00777** [OrchidTechnologies/orchid#66]
**Is your feature request related to a problem? Please describe.**
Right now you have one repo for all applications, this is extremely opaque.

**Describe the solution you'd like**
i would like to see a own repository for the different application you have like
clients (windows,linux...)
server/node (windows,linux,docker...) 
test client
test node
i didnt really understand what all folders are for...
propably you could also create own repos for the different operation systems too

**Improvement**
the Improvement would be that you have a clear repo overview and dont have to waste mutch time in searching between folders when you need something. these would also look more professional (please don't feel offended but it just looks really disgusting right now and completely without any kind of system like a kid would do its first programming steps).
you could take a look at https://github.com/jellyfin there it feels like they have repos for everything and because of that when you know that you have a problem with only one thing you could go to these thing and report it there.

**Comment by saurik** [comment]
No (sorry). On GitHub, there is no good way to transfer issues between repositories, and most people (even very technical ones) don't know in which repository they "should" report an issue. Meanwhile, it is actually quite convenient to know that if you download the code for Orchid you get all of the code for Orchid. I sometimes try to figure out which of the 50-some repositories other projects I am staring at has the code I need, and find myself wasting hours searching and failing. I agree that there needs to be a better README file at the top level of Orchid, but do not see us breaking up our monorepo (and I would actually much prefer to see other projects adopt one, to make it easier to find code and report issues).
