### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by Xyz00777** [OrchidTechnologies/orchid#67]
**Is your feature request related to a problem? Please describe.**
at the moment you have a FAQ with not really much information

**Describe the solution you'd like**
In my opinion you need a wiki who is better like the FAQ site from you
Some information i missing at the moment:
- (detailed) Installation instructions for server/node sites
- better installation and setup instructions for end user like how to create a account (probably YouTube videos) and how to install the software
- system recommendations for server/nodes probably something like a table with amount of connections and for that needed system capabilities. (i know that they can fluctuate depending on what users doing, but estimates are better for users who want to support the project than nothing)
- in depth instructions to set up the client (probably also with videos)

**Additional context**
you could probably use the GitHub wiki or sphinx

**Comment by saurik** [comment]
We will be providing more detailed documentation on these things when we feel there is more need for such documentation. In the mean time, our FAQ is open source (yay!), and so you are welcome to submit pull requests (though I will say that I would appreciate any such to be carefully copy-edited first: get a friend who is good at English to help; requests to add content with broken grammar and poor punctuation will probably languish or even be ignored)... collaboration does not require a hosted, centralized Wiki. If you do choose to help in this regard, we send you our thanks! :D
