### ISSUE TITLE
Broken link on `orchid/blob/master/docs/accounts.md#how-to-get-an-orchid-account`

### ISSUE THREAD

**Issue by lodotek** [OrchidTechnologies/orchid#71]
Broken link  (https://docs.orchid.com/en/stable/orchid-dapp/#create-account) on line `Create and self-custody an Orchid account using the Orchid dApp`

**Comment by saurik** [comment]
I can't find the text "self-custody" anywhere in our application. Can you point at where this link is coming _from_? :(

**Comment by saurik** [comment]
Ah HA! I'm now seeing it (I have no clue what I did wrong before). I've fixed this issue in dd3ac71424be9d1731b2f19b33c46101d3af932a. Thanks for the report!
