### ISSUE TITLE
srv-shared build stuck at building CV8/ICU4U

### ISSUE THREAD

**Issue by ChunbleBee** [OrchidTechnologies/orchid#73]
Using the given makefile for srv-shared, I cannot seem to build past CV8, in particular the ICU4C submodule, on the node/server, despite my best efforts. I seem to be able to build the submodule directly (cding into the directory, then make), but it fails when trying to build from the srv-shared makefile. Make keeps giving me an error that the C Compiler doesn't work, but I've tested gcc and clang with multiple other projects, and it seems to work fine, not to mention that all the other submodules seem to build without issue as well.

**Device information:**
 - Device: Microsoft Surface 3 (Intel Atom x7-8700, 2GB RAM)
 - OS: Ubuntu 20.10
 - Repo Version: Most Current
 - Pretty much every up-to-date C-Compiler available in Apt installed, with Multilib

**Additional context**
Console Output: 
> make -j $(nproc)
> cd out-lnx/x86_64/./cv8/icu/icu4c/ && /home/taiya/orchid/srv-shared/cv8/icu/icu4c/configure --host=x86_64-linux-gnu --prefix=/home/taiya/orchid/srv-shared/out-lnx/x86_64/usr \
>     CC="clang " CFLAGS="-gfull -Os -fdebug-prefix-map=./= -fdebug-prefix-map=/home/taiya/orchid/srv-shared=. -fdata-sections -ffunction-sections -fvisibility=hidden -fPIC -D_LIBCPP_DISABLE_AVAILABILITY -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -DCHROMIUM_ZLIB_NO_CHROMECONF" CXX="clang++ " CXXFLAGS="-gfull -Os -fdebug-prefix-map=./= -fdebug-prefix-map=/home/taiya/orchid/srv-shared=. -fdata-sections -ffunction-sections -fvisibility=hidden -fPIC -D_LIBCPP_DISABLE_AVAILABILITY -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -DCHROMIUM_ZLIB_NO_CHROMECONF -nostdinc++ -isystem /home/taiya/orchid/srv-shared/./env/libcxx/include -isystem /home/taiya/orchid/srv-shared/./env/libcxxabi/include" \
>     RANLIB="ranlib" AR="ar" PKG_CONFIG="/home/taiya/orchid/srv-shared/env/pkg-config" \
>     CPPFLAGS="" \
>     LDFLAGS="-fuse-ld=lld " \
>     --enable-static --disable-shared --with-cross-build=/home/taiya/orchid/srv-shared/out-lnx/icu4c SHELL=/bin/bash
> checking for ICU version numbers... release 68.2, library 68.2, unicode version 13.0
> checking build system type... x86_64-pc-linux-gnu
> checking host system type... x86_64-pc-linux-gnu
> checking whether to build debug libraries... no
> checking whether to build release libraries... yes
> checking for x86_64-linux-gnu-clang... clang 
> checking whether the C compiler works... no
> configure: error: in `/home/taiya/orchid/srv-shared/out-lnx/x86_64/cv8/icu/icu4c':
> configure: error: C compiler cannot create executables
> See `config.log' for more details
> make: *** [env/output.mk:96: out-lnx/x86_64/./cv8/icu/icu4c/Makefile] Error 77

config.log output:

> This file contains any messages produced by compilers while
> running configure, to aid debugging if configure makes a mistake.
> 
> It was created by ICU configure 68.2, which was
> generated by GNU Autoconf 2.69.  Invocation command line was
> 
>   $ /home/taiya/orchid/srv-shared/cv8/icu/icu4c/configure --host=x86_64-linux-gnu --prefix=/home/taiya/orchid/srv-shared/out-lnx/x86_64/usr CC=clang  CFLAGS=-gfull -Os -fdebug-prefix-map=./= -fdebug-prefix-map=/home/taiya/orchid/srv-shared=. -fdata-sections -ffunction-sections -fvisibility=hidden -fPIC -D_LIBCPP_DISABLE_AVAILABILITY -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -DCHROMIUM_ZLIB_NO_CHROMECONF CXX=clang++  CXXFLAGS=-gfull -Os -fdebug-prefix-map=./= -fdebug-prefix-map=/home/taiya/orchid/srv-shared=. -fdata-sections -ffunction-sections -fvisibility=hidden -fPIC -D_LIBCPP_DISABLE_AVAILABILITY -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -DCHROMIUM_ZLIB_NO_CHROMECONF -nostdinc++ -isystem /home/taiya/orchid/srv-shared/./env/libcxx/include -isystem /home/taiya/orchid/srv-shared/./env/libcxxabi/include RANLIB=ranlib AR=ar PKG_CONFIG=/home/taiya/orchid/srv-shared/env/pkg-config CPPFLAGS= LDFLAGS=-fuse-ld=lld  --enable-static --disable-shared --with-cross-build=/home/taiya/orchid/srv-shared/out-lnx/icu4c SHELL=/bin/bash
> 
> ## --------- ##
> ## Platform. ##
> ## --------- ##
> 
> hostname = taiya-Surface-3
> uname -m = x86_64
> uname -r = 5.8.0-44-generic
> uname -s = Linux
> uname -v = #50-Ubuntu SMP Tue Feb 9 06:29:41 UTC 2021
> 
> /usr/bin/uname -p = x86_64
> /bin/uname -X     = unknown
> 
> /bin/arch              = x86_64
> /usr/bin/arch -k       = unknown
> /usr/convex/getsysinfo = unknown
> /usr/bin/hostinfo      = unknown
> /bin/machine           = unknown
> /usr/bin/oslevel       = unknown
> /bin/universe          = unknown
> 
> PATH: /home/taiya/orchid/srv-shared/./env/path
> PATH: /usr/local/sbin
> PATH: /usr/local/bin
> PATH: /usr/sbin
> PATH: /usr/bin
> PATH: /sbin
> PATH: /bin
> PATH: /usr/games
> PATH: /usr/local/games
> PATH: /snap/bin
> 
> 
> ## ----------- ##
> ## Core tests. ##
> ## ----------- ##
> 
> configure:2690: checking for ICU version numbers
> configure:2723: result: release 68.2, library 68.2, unicode version 13.0
> configure:2762: checking build system type
> configure:2776: result: x86_64-pc-linux-gnu
> configure:2796: checking host system type
> configure:2809: result: x86_64-pc-linux-gnu
> configure:2867: checking whether to build debug libraries
> configure:2879: result: no
> configure:2884: checking whether to build release libraries
> configure:2896: result: yes
> configure:2915: checking for x86_64-linux-gnu-clang
> configure:2942: result: clang 
> configure:3017: checking for C compiler version
> configure:3026: clang  --version >&5
> Ubuntu clang version 11.0.0-2
> Target: x86_64-pc-linux-gnu
> Thread model: posix
> InstalledDir: /usr/bin
> configure:3037: $? = 0
> configure:3026: clang  -v >&5
> Ubuntu clang version 11.0.0-2
> Target: x86_64-pc-linux-gnu
> Thread model: posix
> InstalledDir: /usr/bin
> Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/10
> Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
> Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/10
> Candidate multilib: .;@m64
> Candidate multilib: 32;@m32
> Candidate multilib: x32;@mx32
> ... rest of stderr output deleted ...
> configure:3037: $? = 0
> configure:3026: clang  -V >&5
> clang: error: argument to '-V' is missing (expected 1 value)
> clang: error: no input files
> configure:3037: $? = 1
> configure:3026: clang  -qversion >&5
> clang: error: unknown argument '-qversion'; did you mean '--version'?
> clang: error: no input files
> configure:3037: $? = 1
> configure:3057: checking whether the C compiler works
> configure:3079: clang  -gfull -Os -fdebug-prefix-map=./= -fdebug-prefix-map=/home/taiya/orchid/srv-shared=. -fdata-sections -ffunction-sections -fvisibility=hidden -fPIC -D_LIBCPP_DISABLE_AVAILABILITY -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -DCHROMIUM_ZLIB_NO_CHROMECONF  -fuse-ld=lld  conftest.c  >&5
> clang: error: invalid linker name in argument '-fuse-ld=lld'
> configure:3083: $? = 1
> configure:3121: result: no
> configure: failed program was:
> | /* confdefs.h */
> | #define PACKAGE_NAME "ICU"
> | #define PACKAGE_TARNAME "International Components for Unicode"
> | #define PACKAGE_VERSION "68.2"
> | #define PACKAGE_STRING "ICU 68.2"
> | #define PACKAGE_BUGREPORT "http://icu-project.org/bugs"
> | #define PACKAGE_URL "http://icu-project.org"
> | /* end confdefs.h.  */
> | 
> | int
> | main ()
> | {
> | 
> |   ;
> |   return 0;
> | }
> configure:3126: error: in `/home/taiya/orchid/srv-shared/out-lnx/x86_64/cv8/icu/icu4c':
> configure:3128: error: C compiler cannot create executables
> See `config.log' for more details
> 
> ## ---------------- ##
> ## Cache variables. ##
> ## ---------------- ##
> 
> ac_cv_build=x86_64-pc-linux-gnu
> ac_cv_env_CCC_set=
> ac_cv_env_CCC_value=
> ac_cv_env_CC_set=set
> ac_cv_env_CC_value='clang '
> ac_cv_env_CFLAGS_set=set
> ac_cv_env_CFLAGS_value='-gfull -Os -fdebug-prefix-map=./= -fdebug-prefix-map=/home/taiya/orchid/srv-shared=. -fdata-sections -ffunction-sections -fvisibility=hidden -fPIC -D_LIBCPP_DISABLE_AVAILABILITY -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -DCHROMIUM_ZLIB_NO_CHROMECONF'
> ac_cv_env_CPPFLAGS_set=set
> ac_cv_env_CPPFLAGS_value=
> ac_cv_env_CPP_set=
> ac_cv_env_CPP_value=
> ac_cv_env_CXXFLAGS_set=set
> ac_cv_env_CXXFLAGS_value='-gfull -Os -fdebug-prefix-map=./= -fdebug-prefix-map=/home/taiya/orchid/srv-shared=. -fdata-sections -ffunction-sections -fvisibility=hidden -fPIC -D_LIBCPP_DISABLE_AVAILABILITY -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -DCHROMIUM_ZLIB_NO_CHROMECONF -nostdinc++ -isystem /home/taiya/orchid/srv-shared/./env/libcxx/include -isystem /home/taiya/orchid/srv-shared/./env/libcxxabi/include'
> ac_cv_env_CXX_set=set
> ac_cv_env_CXX_value='clang++ '
> ac_cv_env_ICULEHB_CFLAGS_set=
> ac_cv_env_ICULEHB_CFLAGS_value=
> ac_cv_env_ICULEHB_LIBS_set=
> ac_cv_env_ICULEHB_LIBS_value=
> ac_cv_env_LDFLAGS_set=set
> ac_cv_env_LDFLAGS_value='-fuse-ld=lld '
> ac_cv_env_LIBS_set=
> ac_cv_env_LIBS_value=
> ac_cv_env_PKG_CONFIG_LIBDIR_set=
> ac_cv_env_PKG_CONFIG_LIBDIR_value=
> ac_cv_env_PKG_CONFIG_PATH_set=
> ac_cv_env_PKG_CONFIG_PATH_value=
> ac_cv_env_PKG_CONFIG_set=set
> ac_cv_env_PKG_CONFIG_value=/home/taiya/orchid/srv-shared/env/pkg-config
> ac_cv_env_build_alias_set=
> ac_cv_env_build_alias_value=
> ac_cv_env_host_alias_set=set
> ac_cv_env_host_alias_value=x86_64-linux-gnu
> ac_cv_env_target_alias_set=
> ac_cv_env_target_alias_value=
> ac_cv_host=x86_64-pc-linux-gnu
> ac_cv_prog_CC='clang '
> 
> ## ----------------- ##
> ## Output variables. ##
> ## ----------------- ##
> 
> AR='ar'
> ARFLAGS=''
> CC='clang '
> CFLAGS='-gfull -Os -fdebug-prefix-map=./= -fdebug-prefix-map=/home/taiya/orchid/srv-shared=. -fdata-sections -ffunction-sections -fvisibility=hidden -fPIC -D_LIBCPP_DISABLE_AVAILABILITY -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -DCHROMIUM_ZLIB_NO_CHROMECONF'
> COMPILE_LINK_ENVVAR=''
> CPP=''
> CPPFLAGS=''
> CXX='clang++ '
> CXXFLAGS='-gfull -Os -fdebug-prefix-map=./= -fdebug-prefix-map=/home/taiya/orchid/srv-shared=. -fdata-sections -ffunction-sections -fvisibility=hidden -fPIC -D_LIBCPP_DISABLE_AVAILABILITY -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -DCHROMIUM_ZLIB_NO_CHROMECONF -nostdinc++ -isystem /home/taiya/orchid/srv-shared/./env/libcxx/include -isystem /home/taiya/orchid/srv-shared/./env/libcxxabi/include'
> DATA_PACKAGING_MODE=''
> DATA_TRUE=''
> DEFS=''
> DOXYGEN=''
> ECHO_C=''
> ECHO_N='-n'
> ECHO_T=''
> EGREP=''
> ENABLE_DEBUG='0'
> ENABLE_RELEASE='1'
> ENABLE_RPATH=''
> ENABLE_SHARED=''
> ENABLE_STATIC=''
> EXEEXT=''
> EXTRAS_TRUE=''
> FUZZER_TRUE=''
> GENCCODE_ASSEMBLY=''
> GREP=''
> HAVE_MMAP=''
> ICUDATA_CHAR=''
> ICUIO_TRUE=''
> ICULEHB_CFLAGS=''
> ICULEHB_LIBS=''
> ICULIBSUFFIX=''
> ICULIBSUFFIXCNAME=''
> ICU_ECHO_C=''
> ICU_ECHO_N='-n'
> ICU_ECHO_T=''
> INSTALL_DATA=''
> INSTALL_ICU_CONFIG='true'
> INSTALL_PROGRAM=''
> INSTALL_SCRIPT=''
> LAYOUTEX_TRUE=''
> LDFLAGS='-fuse-ld=lld '
> LIBCFLAGS=''
> LIBCXXFLAGS=''
> LIBOBJS=''
> LIBS=''
> LIB_M=''
> LIB_THREAD=''
> LIB_VERSION='68.2'
> LIB_VERSION_MAJOR='68'
> LTLIBOBJS=''
> OBJEXT=''
> PACKAGE='icu'
> PACKAGE_BUGREPORT='http://icu-project.org/bugs'
> PACKAGE_NAME='ICU'
> PACKAGE_STRING='ICU 68.2'
> PACKAGE_TARNAME='International Components for Unicode'
> PACKAGE_URL='http://icu-project.org'
> PACKAGE_VERSION='68.2'
> PATH_SEPARATOR=':'
> PKG_CONFIG='/home/taiya/orchid/srv-shared/env/pkg-config'
> PKG_CONFIG_LIBDIR=''
> PKG_CONFIG_PATH=''
> PLUGINS_TRUE=''
> PYTHON=''
> RANLIB='ranlib'
> SAMPLES_TRUE=''
> SED=''
> SHELL='/bin/bash'
> TESTS_TRUE=''
> TOOLS_TRUE=''
> UCLN_NO_AUTO_CLEANUP=''
> UCONFIG_CFLAGS=''
> UCONFIG_CPPFLAGS=''
> UCONFIG_CXXFLAGS=''
> UNICODE_VERSION='13.0'
> U_DEFAULT_SHOW_DRAFT=''
> U_DISABLE_RENAMING=''
> U_ENABLE_DYLOAD=''
> U_ENABLE_TRACING=''
> U_HAVE_DATA=''
> U_HAVE_DIRENT_H=''
> U_HAVE_EXTRAS=''
> U_HAVE_FUZZER=''
> U_HAVE_ICUIO=''
> U_HAVE_INTTYPES_H=''
> U_HAVE_LAYOUTEX=''
> U_HAVE_LIB_SUFFIX=''
> U_HAVE_NL_LANGINFO_CODESET=''
> U_HAVE_PLACEMENT_NEW=''
> U_HAVE_PLUGINS=''
> U_HAVE_POPEN=''
> U_HAVE_SAMPLES=''
> U_HAVE_STRTOD_L=''
> U_HAVE_TESTS=''
> U_HAVE_TIMEZONE=''
> U_HAVE_TOOLS=''
> U_HAVE_TZNAME=''
> U_HAVE_TZSET=''
> U_HAVE_WCHAR_H=''
> U_HAVE_WCSCPY=''
> U_IS_BIG_ENDIAN=''
> U_MAKE=''
> U_NL_LANGINFO_CODESET=''
> U_OVERRIDE_CXX_ALLOCATION=''
> U_TIMEZONE=''
> U_TZNAME=''
> U_TZSET=''
> VERSION='68.2'
> ac_ct_CC=''
> ac_ct_CXX=''
> bindir='${exec_prefix}/bin'
> build='x86_64-pc-linux-gnu'
> build_alias=''
> build_cpu='x86_64'
> build_os='linux-gnu'
> build_vendor='pc'
> cross_buildroot=''
> cross_compiling='maybe'
> datadir='${datarootdir}'
> datarootdir='${prefix}/share'
> docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
> dvidir='${docdir}'
> exec_prefix='NONE'
> host='x86_64-pc-linux-gnu'
> host_alias='x86_64-linux-gnu'
> host_cpu='x86_64'
> host_os='linux-gnu'
> host_vendor='pc'
> htmldir='${docdir}'
> includedir='${prefix}/include'
> infodir='${datarootdir}/info'
> libdir='${exec_prefix}/lib'
> libexecdir='${exec_prefix}/libexec'
> localedir='${datarootdir}/locale'
> localstatedir='${prefix}/var'
> mandir='${datarootdir}/man'
> oldincludedir='/usr/include'
> pdfdir='${docdir}'
> pkgicudatadir=''
> platform=''
> platform_make_fragment=''
> platform_make_fragment_name=''
> prefix='/home/taiya/orchid/srv-shared/out-lnx/x86_64/usr'
> program_transform_name='s,x,x,'
> psdir='${docdir}'
> sbindir='${exec_prefix}/sbin'
> sharedstatedir='${prefix}/com'
> sysconfdir='${prefix}/etc'
> target_alias=''
> thepkgicudatadir=''
> 
> ## ----------- ##
> ## confdefs.h. ##
> ## ----------- ##
> 
> /* confdefs.h */
> #define PACKAGE_NAME "ICU"
> #define PACKAGE_TARNAME "International Components for Unicode"
> #define PACKAGE_VERSION "68.2"
> #define PACKAGE_STRING "ICU 68.2"
> #define PACKAGE_BUGREPORT "http://icu-project.org/bugs"
> #define PACKAGE_URL "http://icu-project.org"
> 
> configure: exit 77

**Comment by saurik** [comment]
> clang: error: invalid linker name in argument '-fuse-ld=lld'

You need to install lld. If you look in env/setup-lnx.sh you can see all the things our GitHub Ubuntu 20.04 CI installs to make the build work (which includes lld).
