### ISSUE TITLE
The contract GUI for Orchid account creation is confusing

### ISSUE THREAD

**Issue by zjmo** [OrchidTechnologies/orchid#77]
It is very easy to copy the wrong key because it shows the public at the top and the qrcode at the bottom. Would be better to separate the public and show the private not only as qrcode, useful only if one creates the account on a desktop.

**Comment by dereksilva** [comment]
The QR code is useful in any situation, especially if one were to save the PNG.

This GUI is getting a major overhaul, and issues like this are being minimized. Thanks.

**Comment by danopato** [comment]
Signer key generation has been removed from the account manager dapp. The client app separates address and key displays.
