### ISSUE TITLE
The 'Withdraw' page is not clear and the fields are not working as expected

### ISSUE THREAD

**Issue by zjmo** [OrchidTechnologies/orchid#79]
After typing the desired amount to withdraw the field get reset after it loses the focus. Checking the box 'Withdraw full balance and deposit' does not give any kind of information on what is gonna happen. 

![20210315_103831](https://user-images.githubusercontent.com/40869986/111126464-6496ad00-857b-11eb-8f5f-500374943337.jpg)

Android 10, MetaMask App

**Comment by dereksilva** [comment]
Have you unlocked the Deposit?

**Comment by zjmo** [comment]
Yes I did it. The forms don't behave as they should.

**Comment by danopato** [comment]
This form (the whole dapp ui, in fact) has been rebuilt. The behavior that was a problem no longer exists.
