### ISSUE TITLE
Pre-Release Orchid App for Android as APK Download

### ISSUE THREAD

**Issue by Master0ne** [OrchidTechnologies/orchid#8]
Can you please offer the pre-release Orchid app for Android as APK download here in your Github repo?

I have received the mailing today and it is quite disappointing that a Google account for joining the Android Testers Google group is required to acquire the app.

I am using my Android smartphone without Google having LineageOS for microG installed. I want to participate in the pre-release Orchid App testing, but I don't want to have to log into a Google account and join a Google group for it.

**Comment by nhandler** [comment]
Hello,

Thanks for taking the time to report this issue.

A continuous integration action now runs every time a new change is pushed to Github. These builds are untested, but they provide a quick and easy way to get the latest version of the Orchid Android client.

To access the continuous integration builds, go to our Github repository (https://github.com/OrchidTechnologies/orchid) and click on 'Actions'.

Click on the most recent CI event with a green checkmark (✓) to the left of it.

Next, click on 'Artifacts' on the right-hand side of the screen

Finally, select either orchid-apk to download a debug build of the Android client.

For tagged releases, we will publish signed APK files on the GitHub release page. For example, the 0.9.5 version has an APK available for download at https://github.com/OrchidTechnologies/orchid/releases/tag/v0.9.5
