### ISSUE TITLE
Export buttons don't work on Android

### ISSUE THREAD

**Issue by wyphan** [OrchidTechnologies/orchid#94]
**Describe the bug**
On the Android app, the buttons to copy or download the exported account don't work.

**To Reproduce**
1. Use the default user interface (not the Multi-hop UI)
2. Tap "Manage Accounts"
3. Tap the cog wheel next to the Orchid Address gravatar image
4. Tap "Export"
5. Tap either the "Copy" button or the download icon
6. See error

**Expected behavior**
Both the copy and download buttons work to save the exported config.

**Screenshots**
(Note: I blurred the QR code displayed on the screenshot for security reasons)
![Screenshot_20210608-092642](https://user-images.githubusercontent.com/50928756/121196429-7b793280-c83e-11eb-9fa1-fb83a13396d0.png)

**Device information:**
 - Device: Google Pixel 3
 - OS: Android 11 (RQ2A.210505.002)
 - Application Version: 0.9.27, installed from the Play Store

**Additional context**
Can somebody with an iPhone try to check if this problem also exists in the iOS version?

**Comment by wyphan** [comment]
After further investigation, looks like the "Copy" button works, but it doesn't give any feedback to the user so it's impossible to know whether it was successfully copied or not. Maybe implement some kind of toast notification?

**Comment by saurik** [comment]
The copy feedback was added in 58dfd3e4bfdbf49d64367f184ac499f0dc4f0c34 (which will be in the next release) and the download button was removed in 528e1ac36b4d731fb325e46da84746ef6d9a05bd (which will be in the release following that); thanks!! ;P
