### ISSUE TITLE
Windows CLI bug

### ISSUE THREAD

**Issue by victorlane** [OrchidTechnologies/orchid#98]
**Describe the bug**
When running `orchid.exe --config orchid.cfg` I get this error

> [./vpn/p2p/source/execute.hpp:38] system(netsh interface ip set address "Local Area Connection" static 10.7.0.3 255.255.255.0) 
> != 0
> terminate called without an active exception
> [T:3] [vpn/source/capture.cpp:805] orc_trace(): Shut

**To Reproduce**
Follow instructions from blog post https://blog.orchid.com/orchid-is-now-available-in-beta-for-windows-command-line/

**Device information:**
 - OS: Windows 10
 - Application Version: orchidcd-win_0.9.27

**Comment by saurik** [comment]
@victorlane Can you give us the output of "ipconfig /all"?

**Comment by saurik** [comment]
@victorlane Apparently, we also want the output of "route print" and "netsh int ipv4 show interfaces".

**Comment by saurik** [comment]
@victorlane :(

**Comment by saurik** [comment]
(I am closing this bug as the error message from netsh--which would have been printed above those log messages--was not provided and the bug reporter did not provide any follow-up information.)
